# Generated by Django 5.2.17 on 2026-09-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
