# Generated by Django 5.2.17 on 2026-09-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_promocode_commission_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='esewa_product_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='esewa_status',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('manual', 'Manual / QR'), ('esewa', 'eSewa UAT')], default='manual', max_length=20),
        ),
    ]
